# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_01.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 668)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 668))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(20, 10, 771, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_title.setObjectName("label_title")
        self.textBrowser_class = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_class.setGeometry(QtCore.QRect(70, 80, 210, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_class.setFont(font)
        self.textBrowser_class.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textBrowser_class.setObjectName("textBrowser_class")
        self.textBrowser_name = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_name.setGeometry(QtCore.QRect(360, 80, 141, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_name.setFont(font)
        self.textBrowser_name.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textBrowser_name.setObjectName("textBrowser_name")
        self.label_g_id = QtWidgets.QLabel(self.centralwidget)
        self.label_g_id.setGeometry(QtCore.QRect(770, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_g_id.setFont(font)
        self.label_g_id.setObjectName("label_g_id")
        self.label_g_name = QtWidgets.QLabel(self.centralwidget)
        self.label_g_name.setGeometry(QtCore.QRect(770, 220, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_g_name.setFont(font)
        self.label_g_name.setObjectName("label_g_name")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(840, 150, 191, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(840, 220, 191, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(800, 290, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_advanced = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_advanced.setGeometry(QtCore.QRect(780, 550, 131, 41))
        self.pushButton_advanced.setObjectName("pushButton_advanced")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(950, 550, 131, 41))
        self.pushButton_about.setObjectName("pushButton_about")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(20, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_class.setFont(font)
        self.label_class.setObjectName("label_class")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(310, 80, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 130, 721, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_vice = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_vice.setGeometry(QtCore.QRect(0, 370, 731, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser_vice.setFont(font)
        self.textBrowser_vice.setStyleSheet("background-color: rgb(255, 248, 238);")
        self.textBrowser_vice.setObjectName("textBrowser_vice")
        self.textBrowser_main = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_main.setGeometry(QtCore.QRect(0, 0, 731, 371))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser_main.setFont(font)
        self.textBrowser_main.setStyleSheet("background-color: rgb(255, 248, 238);")
        self.textBrowser_main.setObjectName("textBrowser_main")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_more = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_more.setGeometry(QtCore.QRect(0, 0, 731, 441))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser_more.setFont(font)
        self.textBrowser_more.setStyleSheet("background-color: rgb(255, 248, 238);")
        self.textBrowser_more.setObjectName("textBrowser_more")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textBrowser_class, self.textBrowser_name)
        MainWindow.setTabOrder(self.textBrowser_name, self.lineEdit_id)
        MainWindow.setTabOrder(self.lineEdit_id, self.lineEdit_name)
        MainWindow.setTabOrder(self.lineEdit_name, self.pushButton_start)
        MainWindow.setTabOrder(self.pushButton_start, self.pushButton_advanced)
        MainWindow.setTabOrder(self.pushButton_advanced, self.pushButton_about)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "广职院 期末成绩查询器——2019秋季学期"))
        self.label_g_id.setText(_translate("MainWindow", "学号： "))
        self.label_g_name.setText(_translate("MainWindow", "姓名："))
        self.pushButton_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>可能点查询的时候会很卡， 稍微等一下就可以了。</p><p>再不行就重启程序吧。。。</p><p> ╮(﹀_﹀”)╭</p></body></html>"))
        self.pushButton_start.setText(_translate("MainWindow", "查询成绩"))
        self.pushButton_advanced.setText(_translate("MainWindow", "高级功能"))
        self.pushButton_about.setText(_translate("MainWindow", "关于"))
        self.label_class.setText(_translate("MainWindow", "班级："))
        self.label_name.setText(_translate("MainWindow", "姓名："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "&查成绩"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "&更多"))
        self.menu.setTitle(_translate("MainWindow", "保存"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "另存为"))

