# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_03.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Advanced(object):
    def setupUi(self, Advanced):
        Advanced.setObjectName("Advanced")
        Advanced.resize(895, 514)
        self.pushButton_run = QtWidgets.QPushButton(Advanced)
        self.pushButton_run.setGeometry(QtCore.QRect(30, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setObjectName("pushButton_run")
        self.lineEdit_API = QtWidgets.QLineEdit(Advanced)
        self.lineEdit_API.setGeometry(QtCore.QRect(120, 450, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_API.setFont(font)
        self.lineEdit_API.setObjectName("lineEdit_API")
        self.pushButton_add_API = QtWidgets.QPushButton(Advanced)
        self.pushButton_add_API.setGeometry(QtCore.QRect(700, 450, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add_API.setFont(font)
        self.pushButton_add_API.setObjectName("pushButton_add_API")
        self.label = QtWidgets.QLabel(Advanced)
        self.label.setGeometry(QtCore.QRect(10, 450, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Advanced)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Advanced)
        self.label_3.setGeometry(QtCore.QRect(240, 50, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Advanced)
        self.label_4.setGeometry(QtCore.QRect(440, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Advanced)
        self.label_5.setGeometry(QtCore.QRect(490, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Advanced)
        self.label_6.setGeometry(QtCore.QRect(490, 120, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_sc = QtWidgets.QPushButton(Advanced)
        self.pushButton_sc.setGeometry(QtCore.QRect(30, 220, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_sc.setFont(font)
        self.pushButton_sc.setObjectName("pushButton_sc")
        self.label_7 = QtWidgets.QLabel(Advanced)
        self.label_7.setGeometry(QtCore.QRect(260, 220, 411, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Advanced)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(136, 31, 31);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Advanced)
        self.label_9.setGeometry(QtCore.QRect(490, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Advanced)
        QtCore.QMetaObject.connectSlotsByName(Advanced)

    def retranslateUi(self, Advanced):
        _translate = QtCore.QCoreApplication.translate
        Advanced.setWindowTitle(_translate("Advanced", "高级功能"))
        self.pushButton_run.setText(_translate("Advanced", "批量查询成绩 (CLI)"))
        self.pushButton_add_API.setText(_translate("Advanced", "应用"))
        self.label.setText(_translate("Advanced", "更换API接口: "))
        self.label_2.setText(_translate("Advanced", "将用于批量查询的 学号文件命名为 xuehao.txt 放在本程序目录下"))
        self.label_3.setText(_translate("Advanced", "xuehao.txt 文件中每一行的格式为：<学号> <四个空格> <姓名>"))
        self.label_4.setText(_translate("Advanced", "例如: "))
        self.label_5.setText(_translate("Advanced", "1938990112    李华"))
        self.label_6.setText(_translate("Advanced", "1938990114    李小红"))
        self.pushButton_sc.setToolTip(_translate("Advanced", "<html><head/><body><p>配合上一个选项使用</p></body></html>"))
        self.pushButton_sc.setText(_translate("Advanced", "整理得到的 JSON 文件(CLI)"))
        self.label_7.setText(_translate("Advanced", "配合上一个功能使用， 用于处理整理抓取后的生成的json文件"))
        self.label_8.setText(_translate("Advanced", "作者提示： 以上功能需要自己安装 Python 3环境 ，否则是没办法运行的"))
        self.label_9.setText(_translate("Advanced", "1938990111    张小明"))

