# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_02.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ABOUT(object):
    def setupUi(self, ABOUT):
        ABOUT.setObjectName("ABOUT")
        ABOUT.resize(720, 446)
        ABOUT.setMinimumSize(QtCore.QSize(720, 446))
        ABOUT.setMaximumSize(QtCore.QSize(720, 446))
        self.label = QtWidgets.QLabel(ABOUT)
        self.label.setGeometry(QtCore.QRect(50, 20, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ABOUT)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ABOUT)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ABOUT)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ABOUT)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ABOUT)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(ABOUT)
        self.label_7.setGeometry(QtCore.QRect(30, 320, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ABOUT)
        self.label_8.setGeometry(QtCore.QRect(30, 350, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(ABOUT)
        self.label_9.setGeometry(QtCore.QRect(20, 380, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(ABOUT)
        self.label_10.setGeometry(QtCore.QRect(510, 410, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(ABOUT)
        self.label_11.setGeometry(QtCore.QRect(490, 200, 151, 151))
        self.label_11.setStyleSheet("image: url(:/新前缀/f286084d3ca3a38656eaba4724a3125b.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")

        self.retranslateUi(ABOUT)
        QtCore.QMetaObject.connectSlotsByName(ABOUT)

    def retranslateUi(self, ABOUT):
        _translate = QtCore.QCoreApplication.translate
        ABOUT.setWindowTitle(_translate("ABOUT", "关于"))
        self.label.setText(_translate("ABOUT", "因为寒假太冷在家里无聊，打算敲下代码练练手，随便开发了这个查期末成绩的小程序。"))
        self.label_2.setText(_translate("ABOUT", "这个程序主要使用的是 Get data of Python WEB crawler  + Beautifulsoup4 Interface analysis + "))
        self.label_3.setText(_translate("ABOUT", "PYQT5 GUI framework 等相关 import library 进行制作开发的。"))
        self.label_4.setText(_translate("ABOUT", "<html><head/><body><p><a href=\"http://www.xiaotaokeji.com/magicform/query/pc/?form_id=kS6rp1DbawZmiLyY&amp;media_id=1104371724&amp;platform=pc\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.xiaotaokeji.com/magicform/query/pc/?form_id=kS6rp1DbawZmiLyY&amp;media_id=1104371724&amp;platform=pc</span></a></p></body></html>"))
        self.label_5.setText(_translate("ABOUT", "成绩数据相关信息的来源是学校公众号的期末成绩查询网址，有些成绩查不到不是程序的锅.."))
        self.label_6.setText(_translate("ABOUT", "作者： COLDRAIN"))
        self.label_7.setText(_translate("ABOUT", "<html><head/><body><p><a href=\"https://blog.csdn.net/COLDRAIN_END\"><span style=\" text-decoration: underline; color:#0000ff;\">博客：https://blog.csdn.net/COLDRAIN_END</span></a></p></body></html>"))
        self.label_8.setText(_translate("ABOUT", "<html><head/><body><p><a href=\"https://github.com/COLDRAINEND\"><span style=\" text-decoration: underline; color:#0000ff;\">GITHUB：https://github.com/COLDRAINEND</span></a></p></body></html>"))
        self.label_9.setText(_translate("ABOUT", "（注： 本程序仅用于参考,学习,请勿用于任何非法用途）"))
        self.label_10.setText(_translate("ABOUT", "Date: 2020-02-01 PM"))

import t_rc
